name: via_cep
description: Uma biblioteca para consulta de CEP para desenvolvedores Dart (Console, Web e Flutter).
version: 1.0.7
homepage: https://viacep.com.br/
repository: https://github.com/mateuspenha/via_cep
issue_tracker: https://github.com/mateuspenha/via_cep/issues
author: Mateus Penha <mateuspenha@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.13.0
  xml2json: ^4.4.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
